name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install BetterChatGPT dependencies
        working-directory: ./BetterChatGPT
        run: npm ci
      - name: Build app
        working-directory: ./BetterChatGPT
        run: npm run build
        
  chroma-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify ChromaDB server
        run: |
          python -c "import chromadb; import flask; print('Dependencies successfully installed')"

